################################################
#
#
#
#
#
################################################

FROM		ehudkaldor/alpine-rpi:3.5
MAINTAINER	Ehud Kaldor <ehud.kaldor@gmail.com>

ENV		S6_LOGGING 1
ENV		S6_VERSION 1.18.1.5
ENV		ARCH armhf
ADD 		https://github.com/just-containers/s6-overlay/releases/download/v$S6_VERSION/s6-overlay-$ARCH.tar.gz /tmp/
RUN 		gunzip -c /tmp/s6-overlay-$ARCH.tar.gz | tar -xf - -C /

COPY		rootfs /

ENTRYPOINT	["/init"]
